# Generated by Django 4.2.1 on 2023-05-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="descricao",
            field=models.CharField(blank=True, default="", max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="tarefa",
            name="nome",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
    ]
